# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36d223203dd52a9077b6da3140d38202cbe61b1a326772fa92152d50eec639f1a1df34b1226f904662b42f7dd8044d03130c41c0eae95c1bf8d6975159edc7b9

test:
  secret_key_base: 8d43e2e82d27ddb571f0b2da64eae42691e6e73a1dd2f268e8d7676e16888dc6ed2ec4de3c9b467470f93e3e632db7582383703b62e46e2af012700f71823e3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
